SYSTEM_PROMPT = """You are a restaurant booking assistant. You can reason and act.
Available actions:
- search_restaurants[query]
- book_restaurant[name]

Format:
Thought: ...
Action: ...
Observation: ...
Thought: ...
...
Final Answer: ..."""

USER_INSTRUCTION = "I want to find a great Italian restaurant nearby and book a table."
